---
title: "cm-010"
author: "Melanie Ang"
date: '2017-10-05'
output: html_document
---

These are the lecture notes from class (Oct 5 2017).

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load packages
library(tidyverse)
```

```{r}
# Possible joins
left_join()
inner_join()
full_join()
anti_join()
semi_join()
```

```{r}
# server within cran - full packages
# in progress - can download from github
  # via dev tools

# the package we need is on Joey's GitHub:
install.packages("devtools")
library(devtools)
install_github("JoeyBernhardt/singer")

```

Now we have the singer package, download data frames

```{r}
# you can input data files as a .RData on github
library(singer)
data("locations")
data("songs")
glimpse(songs)

View("locations")
```

### Release and Year

Produce a data frame with all the albums ('release'), artist ('artist_name') and the year ('year') in which album was published? We only want values where all are present, no NAs.

```{r}
relartyear <- inner_join(locations, songs, by = "title") %>% #artist name is in both, but not unique
  select(artist_name.x, year, release)

# title.x and title.y
# if there are 2 variables with the same name and they are joined together in the same table

relartyear <- inner_join(locations, songs, by = c("title", "artist_name")) %>% 
  # you can join by both!
  # if both are the same then join!
  select(artist_name, year, release)

```

